import {generateId} from "../../../common/utils/generate-id/generateId";

export const ContactsData = {
    en: {
        title: 'Contact Information',
        description: 'I am based in Minsk, Belarus. You can leave your questions and suggestions. I will gladly review them.',
        text: 'Contacts',
        shadowText: 'Contact Me',
        labelName: 'Name',
        placeholderName: 'Enter your name...',
        labelEmail: 'Email',
        placeholderEmail: 'Enter your email...',
        labelSubject: 'Subject',
        placeholderSubject: 'Enter subject...',
        labelMessage: 'Message',
        placeholderMessage: 'Enter your message...',
        sending: 'Send Mail',
        sendingOK: 'Thanks for your interest! I will contact you as soon as it possible',
        sendingFAIL: 'Something is wrong while sending the message!',
        errorsName: 'Name is required',
        errorsEmail: 'Email is required',
        errorsEmailInvalid: 'Invalid email address',
        errorsSubject: 'Subject is required',
        errorsMessage: 'Message is required',
        info: [
            {
                id: generateId(),
                sprId: 'phone',
                title: 'Contact by phone',
                value: '+375 (29) 397-95-60',
            },
            {
                id: generateId(),
                sprId: 'email',
                title: 'Contact by email',
                value: 'j.popova.dev@gmail.com',
            },
            {
                id: generateId(),
                sprId: 'address',
                title: 'My location',
                value: 'Minsk, Belarus',
            }],
    },
    ru: {
        title: 'Контактная информация',
        description: 'Я живу в Минске, Беларусь. Вы можете написать свои вопросы и предложения. Я с удовольствием их рассмотрю.',
        text: 'Контакты',
        shadowText: 'Связаться',
        labelName: 'Имя',
        placeholderName: 'Введите ваше имя...',
        labelEmail: 'Электронная почта',
        placeholderEmail: 'Введите адрес электронной почты...',
        labelSubject: 'Тема обращения',
        placeholderSubject: 'Тема обращения...',
        labelMessage: 'Сообщение',
        placeholderMessage: 'Написать сообщение...',
        sending: 'Отправить',
        sendingOK: 'Спасибо за ваш интерес! Я свяжусь с вами как можно скорее',
        sendingFAIL: 'Сообщение не отправлено. Пожалуйста, свяжитесь другим способом.',
        errorsName: 'Поле обязательно для заполнения',
        errorsEmail: 'Поле обязательно для заполнения',
        errorsEmailInvalid: 'Неверный адрес электронной почты',
        errorsSubject: 'Поле обязательно для заполнения',
        errorsMessage: 'Поле обязательно для заполнения',
        info: [
            {
                id: generateId(),
                sprId: 'phone',
                title: 'Связаться по телефону',
                value: '+375 (29) 397-95-60',
            },
            {
                id: generateId(),
                sprId: 'email',
                title: 'Связаться по электронной почте',
                value: 'j.popova.dev@gmail.com',
            },
            {
                id: generateId(),
                sprId: 'address',
                title: 'Мое местонахождение',
                value: 'Минск, Беларусь',
            }],
    }
}